"""Shared configuration, data loading, and artifact helpers for GEPA runs."""

from __future__ import annotations

import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence


@dataclass(frozen=True)
class LMSettings:
    base_url: str
    model_name: str
    api_key: str
    temperature: float = 0.0


@dataclass(frozen=True)
class RetrievalSettings:
    url: str
    timeout: float
    top_k: int


@dataclass(frozen=True)
class RunSettings:
    task_lm: LMSettings
    reflection_lm: LMSettings
    retrieval: RetrievalSettings
    input_path: Path
    case_path: Path
    golden_query_path: Path | None
    train_ratio: float
    split_seed: int
    metric_cutoff: int
    max_metric_calls: int
    reflection_minibatch_size: int
    num_threads: int
    output_dir: Path


@dataclass(frozen=True)
class DialogueExample:
    sample_index: int
    call_sno: str | None
    dialogue: str
    expected_case_id: str
    expected_case_title: str


@dataclass(frozen=True)
class GoldenReference:
    """Offline-only reference generated by get_goldenquery."""

    case_title: str
    query: str


def _mapping(payload: Mapping[str, Any], name: str) -> Mapping[str, Any]:
    value = payload.get(name)
    if not isinstance(value, Mapping):
        raise ValueError(f"configuration field '{name}' must be an object")
    return value


def _string(value: Any, name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"configuration field '{name}' must be a non-empty string")
    return value.strip()


def _lm(payload: Mapping[str, Any], name: str) -> LMSettings:
    section = _mapping(payload, name)
    env_name = _string(section.get("api_key_env", "OPENAI_API_KEY"), f"{name}.api_key_env")
    api_key = section.get("api_key") or os.getenv(env_name)
    temperature = section.get("temperature", 0.0)
    if not isinstance(temperature, (int, float)) or isinstance(temperature, bool) or not 0 <= temperature <= 2:
        raise ValueError(f"configuration field '{name}.temperature' must be between 0 and 2")
    return LMSettings(
        base_url=_string(section.get("base_url"), f"{name}.base_url"),
        model_name=_string(section.get("model_name"), f"{name}.model_name"),
        api_key=_string(api_key, f"{name}.api_key or environment variable {env_name}"),
        temperature=float(temperature),
    )


def load_settings(path: str | Path) -> RunSettings:
    config_path = Path(path).resolve()
    try:
        payload = json.loads(config_path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValueError(f"configuration file does not exist: {config_path}") from exc
    if not isinstance(payload, Mapping):
        raise ValueError("configuration root must be a JSON object")

    retrieval = _mapping(payload, "retrieval")
    dataset = _mapping(payload, "dataset")
    optimization = _mapping(payload, "optimization")
    root = config_path.parent
    input_path = Path(_string(dataset.get("input_path"), "dataset.input_path"))
    if not input_path.is_absolute():
        input_path = (root / input_path).resolve()
    case_path = Path(_string(dataset.get("case_path"), "dataset.case_path"))
    if not case_path.is_absolute():
        case_path = (root / case_path).resolve()
    golden_query_path = dataset.get("golden_query_path")
    if golden_query_path is not None:
        golden_query_path = Path(_string(golden_query_path, "dataset.golden_query_path"))
        if not golden_query_path.is_absolute():
            golden_query_path = (root / golden_query_path).resolve()
    output_dir = Path(_string(payload.get("output_dir", "runs"), "output_dir"))
    if not output_dir.is_absolute():
        output_dir = (root / output_dir).resolve()

    def positive_int(value: Any, name: str) -> int:
        if not isinstance(value, int) or isinstance(value, bool) or value < 1:
            raise ValueError(f"configuration field '{name}' must be a positive integer")
        return value

    train_ratio = dataset.get("train_ratio", 0.8)
    if not isinstance(train_ratio, (int, float)) or isinstance(train_ratio, bool) or not 0 < train_ratio < 1:
        raise ValueError("configuration field 'dataset.train_ratio' must be between 0 and 1")
    return RunSettings(
        task_lm=_lm(payload, "task_lm"),
        reflection_lm=_lm(payload, "reflection_lm"),
        retrieval=RetrievalSettings(
            url=_string(retrieval.get("url"), "retrieval.url"),
            timeout=float(retrieval.get("timeout", 30)),
            top_k=positive_int(retrieval.get("top_k", 10), "retrieval.top_k"),
        ),
        input_path=input_path,
        case_path=case_path,
        golden_query_path=golden_query_path,
        train_ratio=float(train_ratio),
        split_seed=int(dataset.get("split_seed", 42)),
        metric_cutoff=positive_int(optimization.get("metric_cutoff", 5), "optimization.metric_cutoff"),
        max_metric_calls=positive_int(optimization.get("max_metric_calls", 100), "optimization.max_metric_calls"),
        reflection_minibatch_size=positive_int(
            optimization.get("reflection_minibatch_size", 3),
            "optimization.reflection_minibatch_size",
        ),
        num_threads=positive_int(optimization.get("num_threads", 1), "optimization.num_threads"),
        output_dir=output_dir,
    )


def load_case_titles(path: str | Path) -> dict[str, str]:
    """Load ``caseID -> title`` from the same formats accepted by golden query generation."""

    source = Path(path)
    try:
        payload = json.loads(source.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValueError(f"case file does not exist: {source}") from exc
    if isinstance(payload, Mapping):
        records = list(payload.items())
    elif isinstance(payload, list):
        records = [
            (item.get("caseID") or item.get("case_id"), item)
            for item in payload
            if isinstance(item, Mapping)
        ]
    else:
        raise ValueError("case JSON must be an object keyed by case ID or a list of case objects")

    titles: dict[str, str] = {}
    for raw_case_id, item in records:
        if not isinstance(item, Mapping) or raw_case_id is None:
            continue
        case_id = str(raw_case_id).strip()
        title = item.get("case_name") or item.get("case_title") or item.get("title")
        if case_id and isinstance(title, str) and title.strip():
            titles[case_id] = title.strip()
    if not titles:
        raise ValueError(f"case file contains no usable case ID/title records: {source}")
    return titles


def load_examples(path: str | Path, case_titles: Mapping[str, str]) -> list[DialogueExample]:
    try:
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValueError(f"dialogue input does not exist: {path}") from exc
    if not isinstance(payload, list):
        raise ValueError("dialogue input must be a JSON array")
    examples: list[DialogueExample] = []
    for index, item in enumerate(payload):
        if not isinstance(item, Mapping):
            continue
        dialogue, case_id = item.get("chat_content"), item.get("caseID")
        if not isinstance(dialogue, str) or not dialogue.strip() or case_id is None or not str(case_id).strip():
            continue
        call_sno = item.get("call_sno")
        normalized_case_id = str(case_id).strip()
        case_title = case_titles.get(normalized_case_id)
        if case_title is None:
            raise ValueError(
                f"dialogue sample {index} references caseID {normalized_case_id!r}, "
                "which has no title in dataset.case_path"
            )
        examples.append(
            DialogueExample(
                index,
                str(call_sno).strip() if call_sno is not None else None,
                dialogue.strip(),
                normalized_case_id,
                case_title,
            )
        )
    if len(examples) < 2:
        raise ValueError("at least two valid dialogue samples with chat_content and caseID are required")
    return examples


def split_examples(examples: Sequence[DialogueExample], train_ratio: float, seed: int) -> tuple[list[DialogueExample], list[DialogueExample]]:
    import random

    shuffled = list(examples)
    random.Random(seed).shuffle(shuffled)
    train_size = min(max(1, round(len(shuffled) * train_ratio)), len(shuffled) - 1)
    return shuffled[:train_size], shuffled[train_size:]


def load_golden_references(path: str | Path | None) -> dict[int, GoldenReference]:
    """Read usable title/query references from a golden-query artifact.

    This is intentionally optional and is only for GEPA's offline reflection.
    The target case title and golden query are never inputs to the query
    generator or exported production prompt.
    """

    if path is None:
        return {}
    source = Path(path)
    try:
        payload = json.loads(source.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValueError(f"golden query artifact does not exist: {source}") from exc
    if not isinstance(payload, Mapping) or payload.get("artifact_type") != "golden_query_generation":
        raise ValueError("golden query input must be a 'golden_query_generation' artifact")
    records = payload.get("records")
    if not isinstance(records, list):
        raise ValueError("golden query artifact 'records' must be a JSON array")
    references: dict[int, GoldenReference] = {}
    for record in records:
        if not isinstance(record, Mapping) or record.get("status") != "success":
            continue
        index = record.get("sample_index")
        query = record.get("final_query")
        case = record.get("golden_case")
        title = case.get("title") if isinstance(case, Mapping) else None
        if isinstance(index, int) and not isinstance(index, bool) and isinstance(query, str) and query.strip() and isinstance(title, str) and title.strip():
            references[index] = GoldenReference(case_title=title.strip(), query=query.strip())
    return references


def write_json(payload: Mapping[str, Any], path: str | Path) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=target.parent, delete=False, suffix=".tmp") as stream:
        json.dump(payload, stream, ensure_ascii=False, indent=2)
        stream.write("\n")
        temporary = Path(stream.name)
    temporary.replace(target)
